version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: eaglys
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
