version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: api
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev
    env_file:
      - .env
