branch-defaults:
  main:
    environment: production
environment-defaults:
  production:
    branch: null
    repository: null
global:
  application_name: eaglys-api
  default_ec2_keyname: eaglys_key_pair
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
